FROM node:20-alpine

WORKDIR /app

COPY Backend/package*.json ./
COPY Backend/prisma ./prisma
COPY Backend/prisma.config.ts ./prisma.config.ts
RUN npm install

COPY Backend/ ./

EXPOSE 3000

CMD ["npm", "run", "start:railway"]