
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ResponseActor = {
  AUTHOR: 'AUTHOR',
  LLM: 'LLM',
  ADMIN: 'ADMIN'
} as const

export type ResponseActor = (typeof ResponseActor)[keyof typeof ResponseActor]
