
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Author: 'Author',
  Admin: 'Admin',
  Book: 'Book',
  Ticket: 'Ticket',
  TicketNote: 'TicketNote',
  TicketMessage: 'TicketMessage'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AuthorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  phone: 'phone',
  city: 'city',
  accountNumber: 'accountNumber',
  joinedDate: 'joinedDate',
  updatedDate: 'updatedDate'
} as const

export type AuthorScalarFieldEnum = (typeof AuthorScalarFieldEnum)[keyof typeof AuthorScalarFieldEnum]


export const AdminScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  contactInfo: 'contactInfo',
  joinedDate: 'joinedDate',
  updatedDate: 'updatedDate'
} as const

export type AdminScalarFieldEnum = (typeof AdminScalarFieldEnum)[keyof typeof AdminScalarFieldEnum]


export const BookScalarFieldEnum = {
  id: 'id',
  authorId: 'authorId',
  title: 'title',
  isbn: 'isbn',
  status: 'status',
  genre: 'genre',
  publicationDate: 'publicationDate',
  mrp: 'mrp',
  authorRoyaltyPerCopy: 'authorRoyaltyPerCopy',
  totalCopiesSold: 'totalCopiesSold',
  totalRoyaltyEarned: 'totalRoyaltyEarned',
  royaltyPaid: 'royaltyPaid',
  royaltyPending: 'royaltyPending',
  lastRoyaltyPayoutDate: 'lastRoyaltyPayoutDate',
  printPartner: 'printPartner',
  availableOn: 'availableOn',
  createdDate: 'createdDate',
  updatedDate: 'updatedDate'
} as const

export type BookScalarFieldEnum = (typeof BookScalarFieldEnum)[keyof typeof BookScalarFieldEnum]


export const TicketScalarFieldEnum = {
  id: 'id',
  authorId: 'authorId',
  category: 'category',
  bookId: 'bookId',
  header: 'header',
  detailDescription: 'detailDescription',
  status: 'status',
  assignedId: 'assignedId',
  priorityScore: 'priorityScore',
  aiDraft: 'aiDraft',
  createdDate: 'createdDate',
  updatedDate: 'updatedDate',
  resolvedDate: 'resolvedDate'
} as const

export type TicketScalarFieldEnum = (typeof TicketScalarFieldEnum)[keyof typeof TicketScalarFieldEnum]


export const TicketNoteScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  adminId: 'adminId',
  message: 'message',
  visibility: 'visibility'
} as const

export type TicketNoteScalarFieldEnum = (typeof TicketNoteScalarFieldEnum)[keyof typeof TicketNoteScalarFieldEnum]


export const TicketMessageScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  responseActor: 'responseActor',
  message: 'message',
  createdAt: 'createdAt'
} as const

export type TicketMessageScalarFieldEnum = (typeof TicketMessageScalarFieldEnum)[keyof typeof TicketMessageScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

