
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Ticket` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Ticket
 * 
 */
export type TicketModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketPayload>

export type AggregateTicket = {
  _count: TicketCountAggregateOutputType | null
  _avg: TicketAvgAggregateOutputType | null
  _sum: TicketSumAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

export type TicketAvgAggregateOutputType = {
  priorityScore: number | null
}

export type TicketSumAggregateOutputType = {
  priorityScore: number | null
}

export type TicketMinAggregateOutputType = {
  id: string | null
  authorId: string | null
  category: string | null
  bookId: string | null
  header: string | null
  detailDescription: string | null
  status: string | null
  assignedId: string | null
  priorityScore: number | null
  aiDraft: string | null
  createdDate: Date | null
  updatedDate: Date | null
  resolvedDate: Date | null
}

export type TicketMaxAggregateOutputType = {
  id: string | null
  authorId: string | null
  category: string | null
  bookId: string | null
  header: string | null
  detailDescription: string | null
  status: string | null
  assignedId: string | null
  priorityScore: number | null
  aiDraft: string | null
  createdDate: Date | null
  updatedDate: Date | null
  resolvedDate: Date | null
}

export type TicketCountAggregateOutputType = {
  id: number
  authorId: number
  category: number
  bookId: number
  header: number
  detailDescription: number
  status: number
  assignedId: number
  priorityScore: number
  aiDraft: number
  createdDate: number
  updatedDate: number
  resolvedDate: number
  _all: number
}


export type TicketAvgAggregateInputType = {
  priorityScore?: true
}

export type TicketSumAggregateInputType = {
  priorityScore?: true
}

export type TicketMinAggregateInputType = {
  id?: true
  authorId?: true
  category?: true
  bookId?: true
  header?: true
  detailDescription?: true
  status?: true
  assignedId?: true
  priorityScore?: true
  aiDraft?: true
  createdDate?: true
  updatedDate?: true
  resolvedDate?: true
}

export type TicketMaxAggregateInputType = {
  id?: true
  authorId?: true
  category?: true
  bookId?: true
  header?: true
  detailDescription?: true
  status?: true
  assignedId?: true
  priorityScore?: true
  aiDraft?: true
  createdDate?: true
  updatedDate?: true
  resolvedDate?: true
}

export type TicketCountAggregateInputType = {
  id?: true
  authorId?: true
  category?: true
  bookId?: true
  header?: true
  detailDescription?: true
  status?: true
  assignedId?: true
  priorityScore?: true
  aiDraft?: true
  createdDate?: true
  updatedDate?: true
  resolvedDate?: true
  _all?: true
}

export type TicketAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ticket to aggregate.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tickets
  **/
  _count?: true | TicketCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketMaxAggregateInputType
}

export type GetTicketAggregateType<T extends TicketAggregateArgs> = {
      [P in keyof T & keyof AggregateTicket]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicket[P]>
    : Prisma.GetScalarType<T[P], AggregateTicket[P]>
}




export type TicketGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketWhereInput
  orderBy?: Prisma.TicketOrderByWithAggregationInput | Prisma.TicketOrderByWithAggregationInput[]
  by: Prisma.TicketScalarFieldEnum[] | Prisma.TicketScalarFieldEnum
  having?: Prisma.TicketScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketCountAggregateInputType | true
  _avg?: TicketAvgAggregateInputType
  _sum?: TicketSumAggregateInputType
  _min?: TicketMinAggregateInputType
  _max?: TicketMaxAggregateInputType
}

export type TicketGroupByOutputType = {
  id: string
  authorId: string
  category: string
  bookId: string | null
  header: string
  detailDescription: string
  status: string
  assignedId: string | null
  priorityScore: number | null
  aiDraft: string | null
  createdDate: Date
  updatedDate: Date
  resolvedDate: Date | null
  _count: TicketCountAggregateOutputType | null
  _avg: TicketAvgAggregateOutputType | null
  _sum: TicketSumAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

export type GetTicketGroupByPayload<T extends TicketGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
      }
    >
  >



export type TicketWhereInput = {
  AND?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  OR?: Prisma.TicketWhereInput[]
  NOT?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  id?: Prisma.StringFilter<"Ticket"> | string
  authorId?: Prisma.StringFilter<"Ticket"> | string
  category?: Prisma.StringFilter<"Ticket"> | string
  bookId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  header?: Prisma.StringFilter<"Ticket"> | string
  detailDescription?: Prisma.StringFilter<"Ticket"> | string
  status?: Prisma.StringFilter<"Ticket"> | string
  assignedId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  priorityScore?: Prisma.IntNullableFilter<"Ticket"> | number | null
  aiDraft?: Prisma.StringNullableFilter<"Ticket"> | string | null
  createdDate?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  updatedDate?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  resolvedDate?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  author?: Prisma.XOR<Prisma.AuthorScalarRelationFilter, Prisma.AuthorWhereInput>
  book?: Prisma.XOR<Prisma.BookNullableScalarRelationFilter, Prisma.BookWhereInput> | null
  assignedAdmin?: Prisma.XOR<Prisma.AdminNullableScalarRelationFilter, Prisma.AdminWhereInput> | null
  notes?: Prisma.TicketNoteListRelationFilter
  messages?: Prisma.TicketMessageListRelationFilter
}

export type TicketOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  bookId?: Prisma.SortOrderInput | Prisma.SortOrder
  header?: Prisma.SortOrder
  detailDescription?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedId?: Prisma.SortOrderInput | Prisma.SortOrder
  priorityScore?: Prisma.SortOrderInput | Prisma.SortOrder
  aiDraft?: Prisma.SortOrderInput | Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  resolvedDate?: Prisma.SortOrderInput | Prisma.SortOrder
  author?: Prisma.AuthorOrderByWithRelationInput
  book?: Prisma.BookOrderByWithRelationInput
  assignedAdmin?: Prisma.AdminOrderByWithRelationInput
  notes?: Prisma.TicketNoteOrderByRelationAggregateInput
  messages?: Prisma.TicketMessageOrderByRelationAggregateInput
}

export type TicketWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  OR?: Prisma.TicketWhereInput[]
  NOT?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  authorId?: Prisma.StringFilter<"Ticket"> | string
  category?: Prisma.StringFilter<"Ticket"> | string
  bookId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  header?: Prisma.StringFilter<"Ticket"> | string
  detailDescription?: Prisma.StringFilter<"Ticket"> | string
  status?: Prisma.StringFilter<"Ticket"> | string
  assignedId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  priorityScore?: Prisma.IntNullableFilter<"Ticket"> | number | null
  aiDraft?: Prisma.StringNullableFilter<"Ticket"> | string | null
  createdDate?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  updatedDate?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  resolvedDate?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  author?: Prisma.XOR<Prisma.AuthorScalarRelationFilter, Prisma.AuthorWhereInput>
  book?: Prisma.XOR<Prisma.BookNullableScalarRelationFilter, Prisma.BookWhereInput> | null
  assignedAdmin?: Prisma.XOR<Prisma.AdminNullableScalarRelationFilter, Prisma.AdminWhereInput> | null
  notes?: Prisma.TicketNoteListRelationFilter
  messages?: Prisma.TicketMessageListRelationFilter
}, "id">

export type TicketOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  bookId?: Prisma.SortOrderInput | Prisma.SortOrder
  header?: Prisma.SortOrder
  detailDescription?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedId?: Prisma.SortOrderInput | Prisma.SortOrder
  priorityScore?: Prisma.SortOrderInput | Prisma.SortOrder
  aiDraft?: Prisma.SortOrderInput | Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  resolvedDate?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TicketCountOrderByAggregateInput
  _avg?: Prisma.TicketAvgOrderByAggregateInput
  _max?: Prisma.TicketMaxOrderByAggregateInput
  _min?: Prisma.TicketMinOrderByAggregateInput
  _sum?: Prisma.TicketSumOrderByAggregateInput
}

export type TicketScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketScalarWhereWithAggregatesInput | Prisma.TicketScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketScalarWhereWithAggregatesInput | Prisma.TicketScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  authorId?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  category?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  bookId?: Prisma.StringNullableWithAggregatesFilter<"Ticket"> | string | null
  header?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  detailDescription?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  status?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  assignedId?: Prisma.StringNullableWithAggregatesFilter<"Ticket"> | string | null
  priorityScore?: Prisma.IntNullableWithAggregatesFilter<"Ticket"> | number | null
  aiDraft?: Prisma.StringNullableWithAggregatesFilter<"Ticket"> | string | null
  createdDate?: Prisma.DateTimeWithAggregatesFilter<"Ticket"> | Date | string
  updatedDate?: Prisma.DateTimeWithAggregatesFilter<"Ticket"> | Date | string
  resolvedDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Ticket"> | Date | string | null
}

export type TicketCreateInput = {
  id?: string
  category: string
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  author: Prisma.AuthorCreateNestedOneWithoutTicketsInput
  book?: Prisma.BookCreateNestedOneWithoutTicketsInput
  assignedAdmin?: Prisma.AdminCreateNestedOneWithoutAssignedInput
  notes?: Prisma.TicketNoteCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateInput = {
  id?: string
  authorId: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  notes?: Prisma.TicketNoteUncheckedCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  author?: Prisma.AuthorUpdateOneRequiredWithoutTicketsNestedInput
  book?: Prisma.BookUpdateOneWithoutTicketsNestedInput
  assignedAdmin?: Prisma.AdminUpdateOneWithoutAssignedNestedInput
  notes?: Prisma.TicketNoteUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.TicketNoteUncheckedUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketCreateManyInput = {
  id?: string
  authorId: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
}

export type TicketUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketListRelationFilter = {
  every?: Prisma.TicketWhereInput
  some?: Prisma.TicketWhereInput
  none?: Prisma.TicketWhereInput
}

export type TicketOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  header?: Prisma.SortOrder
  detailDescription?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedId?: Prisma.SortOrder
  priorityScore?: Prisma.SortOrder
  aiDraft?: Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  resolvedDate?: Prisma.SortOrder
}

export type TicketAvgOrderByAggregateInput = {
  priorityScore?: Prisma.SortOrder
}

export type TicketMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  header?: Prisma.SortOrder
  detailDescription?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedId?: Prisma.SortOrder
  priorityScore?: Prisma.SortOrder
  aiDraft?: Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  resolvedDate?: Prisma.SortOrder
}

export type TicketMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  header?: Prisma.SortOrder
  detailDescription?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedId?: Prisma.SortOrder
  priorityScore?: Prisma.SortOrder
  aiDraft?: Prisma.SortOrder
  createdDate?: Prisma.SortOrder
  updatedDate?: Prisma.SortOrder
  resolvedDate?: Prisma.SortOrder
}

export type TicketSumOrderByAggregateInput = {
  priorityScore?: Prisma.SortOrder
}

export type TicketScalarRelationFilter = {
  is?: Prisma.TicketWhereInput
  isNot?: Prisma.TicketWhereInput
}

export type TicketCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAuthorInput, Prisma.TicketUncheckedCreateWithoutAuthorInput> | Prisma.TicketCreateWithoutAuthorInput[] | Prisma.TicketUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAuthorInput | Prisma.TicketCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TicketCreateManyAuthorInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAuthorInput, Prisma.TicketUncheckedCreateWithoutAuthorInput> | Prisma.TicketCreateWithoutAuthorInput[] | Prisma.TicketUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAuthorInput | Prisma.TicketCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TicketCreateManyAuthorInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAuthorInput, Prisma.TicketUncheckedCreateWithoutAuthorInput> | Prisma.TicketCreateWithoutAuthorInput[] | Prisma.TicketUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAuthorInput | Prisma.TicketCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TicketUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TicketCreateManyAuthorInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TicketUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutAuthorInput | Prisma.TicketUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAuthorInput, Prisma.TicketUncheckedCreateWithoutAuthorInput> | Prisma.TicketCreateWithoutAuthorInput[] | Prisma.TicketUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAuthorInput | Prisma.TicketCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TicketUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TicketCreateManyAuthorInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TicketUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutAuthorInput | Prisma.TicketUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketCreateNestedManyWithoutAssignedAdminInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAssignedAdminInput, Prisma.TicketUncheckedCreateWithoutAssignedAdminInput> | Prisma.TicketCreateWithoutAssignedAdminInput[] | Prisma.TicketUncheckedCreateWithoutAssignedAdminInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAssignedAdminInput | Prisma.TicketCreateOrConnectWithoutAssignedAdminInput[]
  createMany?: Prisma.TicketCreateManyAssignedAdminInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUncheckedCreateNestedManyWithoutAssignedAdminInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAssignedAdminInput, Prisma.TicketUncheckedCreateWithoutAssignedAdminInput> | Prisma.TicketCreateWithoutAssignedAdminInput[] | Prisma.TicketUncheckedCreateWithoutAssignedAdminInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAssignedAdminInput | Prisma.TicketCreateOrConnectWithoutAssignedAdminInput[]
  createMany?: Prisma.TicketCreateManyAssignedAdminInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUpdateManyWithoutAssignedAdminNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAssignedAdminInput, Prisma.TicketUncheckedCreateWithoutAssignedAdminInput> | Prisma.TicketCreateWithoutAssignedAdminInput[] | Prisma.TicketUncheckedCreateWithoutAssignedAdminInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAssignedAdminInput | Prisma.TicketCreateOrConnectWithoutAssignedAdminInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutAssignedAdminInput | Prisma.TicketUpsertWithWhereUniqueWithoutAssignedAdminInput[]
  createMany?: Prisma.TicketCreateManyAssignedAdminInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutAssignedAdminInput | Prisma.TicketUpdateWithWhereUniqueWithoutAssignedAdminInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutAssignedAdminInput | Prisma.TicketUpdateManyWithWhereWithoutAssignedAdminInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketUncheckedUpdateManyWithoutAssignedAdminNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutAssignedAdminInput, Prisma.TicketUncheckedCreateWithoutAssignedAdminInput> | Prisma.TicketCreateWithoutAssignedAdminInput[] | Prisma.TicketUncheckedCreateWithoutAssignedAdminInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutAssignedAdminInput | Prisma.TicketCreateOrConnectWithoutAssignedAdminInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutAssignedAdminInput | Prisma.TicketUpsertWithWhereUniqueWithoutAssignedAdminInput[]
  createMany?: Prisma.TicketCreateManyAssignedAdminInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutAssignedAdminInput | Prisma.TicketUpdateWithWhereUniqueWithoutAssignedAdminInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutAssignedAdminInput | Prisma.TicketUpdateManyWithWhereWithoutAssignedAdminInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketCreateNestedManyWithoutBookInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutBookInput, Prisma.TicketUncheckedCreateWithoutBookInput> | Prisma.TicketCreateWithoutBookInput[] | Prisma.TicketUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutBookInput | Prisma.TicketCreateOrConnectWithoutBookInput[]
  createMany?: Prisma.TicketCreateManyBookInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUncheckedCreateNestedManyWithoutBookInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutBookInput, Prisma.TicketUncheckedCreateWithoutBookInput> | Prisma.TicketCreateWithoutBookInput[] | Prisma.TicketUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutBookInput | Prisma.TicketCreateOrConnectWithoutBookInput[]
  createMany?: Prisma.TicketCreateManyBookInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUpdateManyWithoutBookNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutBookInput, Prisma.TicketUncheckedCreateWithoutBookInput> | Prisma.TicketCreateWithoutBookInput[] | Prisma.TicketUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutBookInput | Prisma.TicketCreateOrConnectWithoutBookInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutBookInput | Prisma.TicketUpsertWithWhereUniqueWithoutBookInput[]
  createMany?: Prisma.TicketCreateManyBookInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutBookInput | Prisma.TicketUpdateWithWhereUniqueWithoutBookInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutBookInput | Prisma.TicketUpdateManyWithWhereWithoutBookInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketUncheckedUpdateManyWithoutBookNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutBookInput, Prisma.TicketUncheckedCreateWithoutBookInput> | Prisma.TicketCreateWithoutBookInput[] | Prisma.TicketUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutBookInput | Prisma.TicketCreateOrConnectWithoutBookInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutBookInput | Prisma.TicketUpsertWithWhereUniqueWithoutBookInput[]
  createMany?: Prisma.TicketCreateManyBookInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutBookInput | Prisma.TicketUpdateWithWhereUniqueWithoutBookInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutBookInput | Prisma.TicketUpdateManyWithWhereWithoutBookInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TicketCreateNestedOneWithoutNotesInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutNotesInput, Prisma.TicketUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutNotesInput
  connect?: Prisma.TicketWhereUniqueInput
}

export type TicketUpdateOneRequiredWithoutNotesNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutNotesInput, Prisma.TicketUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutNotesInput
  upsert?: Prisma.TicketUpsertWithoutNotesInput
  connect?: Prisma.TicketWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TicketUpdateToOneWithWhereWithoutNotesInput, Prisma.TicketUpdateWithoutNotesInput>, Prisma.TicketUncheckedUpdateWithoutNotesInput>
}

export type TicketCreateNestedOneWithoutMessagesInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutMessagesInput, Prisma.TicketUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutMessagesInput
  connect?: Prisma.TicketWhereUniqueInput
}

export type TicketUpdateOneRequiredWithoutMessagesNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutMessagesInput, Prisma.TicketUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutMessagesInput
  upsert?: Prisma.TicketUpsertWithoutMessagesInput
  connect?: Prisma.TicketWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TicketUpdateToOneWithWhereWithoutMessagesInput, Prisma.TicketUpdateWithoutMessagesInput>, Prisma.TicketUncheckedUpdateWithoutMessagesInput>
}

export type TicketCreateWithoutAuthorInput = {
  id?: string
  category: string
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  book?: Prisma.BookCreateNestedOneWithoutTicketsInput
  assignedAdmin?: Prisma.AdminCreateNestedOneWithoutAssignedInput
  notes?: Prisma.TicketNoteCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateWithoutAuthorInput = {
  id?: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  notes?: Prisma.TicketNoteUncheckedCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketCreateOrConnectWithoutAuthorInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutAuthorInput, Prisma.TicketUncheckedCreateWithoutAuthorInput>
}

export type TicketCreateManyAuthorInputEnvelope = {
  data: Prisma.TicketCreateManyAuthorInput | Prisma.TicketCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type TicketUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TicketWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketUpdateWithoutAuthorInput, Prisma.TicketUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutAuthorInput, Prisma.TicketUncheckedCreateWithoutAuthorInput>
}

export type TicketUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TicketWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutAuthorInput, Prisma.TicketUncheckedUpdateWithoutAuthorInput>
}

export type TicketUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.TicketScalarWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyWithoutAuthorInput>
}

export type TicketScalarWhereInput = {
  AND?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
  OR?: Prisma.TicketScalarWhereInput[]
  NOT?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
  id?: Prisma.StringFilter<"Ticket"> | string
  authorId?: Prisma.StringFilter<"Ticket"> | string
  category?: Prisma.StringFilter<"Ticket"> | string
  bookId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  header?: Prisma.StringFilter<"Ticket"> | string
  detailDescription?: Prisma.StringFilter<"Ticket"> | string
  status?: Prisma.StringFilter<"Ticket"> | string
  assignedId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  priorityScore?: Prisma.IntNullableFilter<"Ticket"> | number | null
  aiDraft?: Prisma.StringNullableFilter<"Ticket"> | string | null
  createdDate?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  updatedDate?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  resolvedDate?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
}

export type TicketCreateWithoutAssignedAdminInput = {
  id?: string
  category: string
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  author: Prisma.AuthorCreateNestedOneWithoutTicketsInput
  book?: Prisma.BookCreateNestedOneWithoutTicketsInput
  notes?: Prisma.TicketNoteCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateWithoutAssignedAdminInput = {
  id?: string
  authorId: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  notes?: Prisma.TicketNoteUncheckedCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketCreateOrConnectWithoutAssignedAdminInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutAssignedAdminInput, Prisma.TicketUncheckedCreateWithoutAssignedAdminInput>
}

export type TicketCreateManyAssignedAdminInputEnvelope = {
  data: Prisma.TicketCreateManyAssignedAdminInput | Prisma.TicketCreateManyAssignedAdminInput[]
  skipDuplicates?: boolean
}

export type TicketUpsertWithWhereUniqueWithoutAssignedAdminInput = {
  where: Prisma.TicketWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketUpdateWithoutAssignedAdminInput, Prisma.TicketUncheckedUpdateWithoutAssignedAdminInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutAssignedAdminInput, Prisma.TicketUncheckedCreateWithoutAssignedAdminInput>
}

export type TicketUpdateWithWhereUniqueWithoutAssignedAdminInput = {
  where: Prisma.TicketWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutAssignedAdminInput, Prisma.TicketUncheckedUpdateWithoutAssignedAdminInput>
}

export type TicketUpdateManyWithWhereWithoutAssignedAdminInput = {
  where: Prisma.TicketScalarWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyWithoutAssignedAdminInput>
}

export type TicketCreateWithoutBookInput = {
  id?: string
  category: string
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  author: Prisma.AuthorCreateNestedOneWithoutTicketsInput
  assignedAdmin?: Prisma.AdminCreateNestedOneWithoutAssignedInput
  notes?: Prisma.TicketNoteCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateWithoutBookInput = {
  id?: string
  authorId: string
  category: string
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  notes?: Prisma.TicketNoteUncheckedCreateNestedManyWithoutTicketInput
  messages?: Prisma.TicketMessageUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketCreateOrConnectWithoutBookInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutBookInput, Prisma.TicketUncheckedCreateWithoutBookInput>
}

export type TicketCreateManyBookInputEnvelope = {
  data: Prisma.TicketCreateManyBookInput | Prisma.TicketCreateManyBookInput[]
  skipDuplicates?: boolean
}

export type TicketUpsertWithWhereUniqueWithoutBookInput = {
  where: Prisma.TicketWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketUpdateWithoutBookInput, Prisma.TicketUncheckedUpdateWithoutBookInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutBookInput, Prisma.TicketUncheckedCreateWithoutBookInput>
}

export type TicketUpdateWithWhereUniqueWithoutBookInput = {
  where: Prisma.TicketWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutBookInput, Prisma.TicketUncheckedUpdateWithoutBookInput>
}

export type TicketUpdateManyWithWhereWithoutBookInput = {
  where: Prisma.TicketScalarWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyWithoutBookInput>
}

export type TicketCreateWithoutNotesInput = {
  id?: string
  category: string
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  author: Prisma.AuthorCreateNestedOneWithoutTicketsInput
  book?: Prisma.BookCreateNestedOneWithoutTicketsInput
  assignedAdmin?: Prisma.AdminCreateNestedOneWithoutAssignedInput
  messages?: Prisma.TicketMessageCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateWithoutNotesInput = {
  id?: string
  authorId: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  messages?: Prisma.TicketMessageUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketCreateOrConnectWithoutNotesInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutNotesInput, Prisma.TicketUncheckedCreateWithoutNotesInput>
}

export type TicketUpsertWithoutNotesInput = {
  update: Prisma.XOR<Prisma.TicketUpdateWithoutNotesInput, Prisma.TicketUncheckedUpdateWithoutNotesInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutNotesInput, Prisma.TicketUncheckedCreateWithoutNotesInput>
  where?: Prisma.TicketWhereInput
}

export type TicketUpdateToOneWithWhereWithoutNotesInput = {
  where?: Prisma.TicketWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutNotesInput, Prisma.TicketUncheckedUpdateWithoutNotesInput>
}

export type TicketUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  author?: Prisma.AuthorUpdateOneRequiredWithoutTicketsNestedInput
  book?: Prisma.BookUpdateOneWithoutTicketsNestedInput
  assignedAdmin?: Prisma.AdminUpdateOneWithoutAssignedNestedInput
  messages?: Prisma.TicketMessageUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  messages?: Prisma.TicketMessageUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketCreateWithoutMessagesInput = {
  id?: string
  category: string
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  author: Prisma.AuthorCreateNestedOneWithoutTicketsInput
  book?: Prisma.BookCreateNestedOneWithoutTicketsInput
  assignedAdmin?: Prisma.AdminCreateNestedOneWithoutAssignedInput
  notes?: Prisma.TicketNoteCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateWithoutMessagesInput = {
  id?: string
  authorId: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
  notes?: Prisma.TicketNoteUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketCreateOrConnectWithoutMessagesInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutMessagesInput, Prisma.TicketUncheckedCreateWithoutMessagesInput>
}

export type TicketUpsertWithoutMessagesInput = {
  update: Prisma.XOR<Prisma.TicketUpdateWithoutMessagesInput, Prisma.TicketUncheckedUpdateWithoutMessagesInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutMessagesInput, Prisma.TicketUncheckedCreateWithoutMessagesInput>
  where?: Prisma.TicketWhereInput
}

export type TicketUpdateToOneWithWhereWithoutMessagesInput = {
  where?: Prisma.TicketWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutMessagesInput, Prisma.TicketUncheckedUpdateWithoutMessagesInput>
}

export type TicketUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  author?: Prisma.AuthorUpdateOneRequiredWithoutTicketsNestedInput
  book?: Prisma.BookUpdateOneWithoutTicketsNestedInput
  assignedAdmin?: Prisma.AdminUpdateOneWithoutAssignedNestedInput
  notes?: Prisma.TicketNoteUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.TicketNoteUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketCreateManyAuthorInput = {
  id?: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
}

export type TicketUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  book?: Prisma.BookUpdateOneWithoutTicketsNestedInput
  assignedAdmin?: Prisma.AdminUpdateOneWithoutAssignedNestedInput
  notes?: Prisma.TicketNoteUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.TicketNoteUncheckedUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketCreateManyAssignedAdminInput = {
  id?: string
  authorId: string
  category: string
  bookId?: string | null
  header: string
  detailDescription: string
  status: string
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
}

export type TicketUpdateWithoutAssignedAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  author?: Prisma.AuthorUpdateOneRequiredWithoutTicketsNestedInput
  book?: Prisma.BookUpdateOneWithoutTicketsNestedInput
  notes?: Prisma.TicketNoteUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateWithoutAssignedAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.TicketNoteUncheckedUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateManyWithoutAssignedAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketCreateManyBookInput = {
  id?: string
  authorId: string
  category: string
  header: string
  detailDescription: string
  status: string
  assignedId?: string | null
  priorityScore?: number | null
  aiDraft?: string | null
  createdDate?: Date | string
  updatedDate?: Date | string
  resolvedDate?: Date | string | null
}

export type TicketUpdateWithoutBookInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  author?: Prisma.AuthorUpdateOneRequiredWithoutTicketsNestedInput
  assignedAdmin?: Prisma.AdminUpdateOneWithoutAssignedNestedInput
  notes?: Prisma.TicketNoteUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateWithoutBookInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.TicketNoteUncheckedUpdateManyWithoutTicketNestedInput
  messages?: Prisma.TicketMessageUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateManyWithoutBookInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  header?: Prisma.StringFieldUpdateOperationsInput | string
  detailDescription?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorityScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  aiDraft?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type TicketCountOutputType
 */

export type TicketCountOutputType = {
  notes: number
  messages: number
}

export type TicketCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  notes?: boolean | TicketCountOutputTypeCountNotesArgs
  messages?: boolean | TicketCountOutputTypeCountMessagesArgs
}

/**
 * TicketCountOutputType without action
 */
export type TicketCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketCountOutputType
   */
  select?: Prisma.TicketCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TicketCountOutputType without action
 */
export type TicketCountOutputTypeCountNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketNoteWhereInput
}

/**
 * TicketCountOutputType without action
 */
export type TicketCountOutputTypeCountMessagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketMessageWhereInput
}


export type TicketSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  authorId?: boolean
  category?: boolean
  bookId?: boolean
  header?: boolean
  detailDescription?: boolean
  status?: boolean
  assignedId?: boolean
  priorityScore?: boolean
  aiDraft?: boolean
  createdDate?: boolean
  updatedDate?: boolean
  resolvedDate?: boolean
  author?: boolean | Prisma.AuthorDefaultArgs<ExtArgs>
  book?: boolean | Prisma.Ticket$bookArgs<ExtArgs>
  assignedAdmin?: boolean | Prisma.Ticket$assignedAdminArgs<ExtArgs>
  notes?: boolean | Prisma.Ticket$notesArgs<ExtArgs>
  messages?: boolean | Prisma.Ticket$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.TicketCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  authorId?: boolean
  category?: boolean
  bookId?: boolean
  header?: boolean
  detailDescription?: boolean
  status?: boolean
  assignedId?: boolean
  priorityScore?: boolean
  aiDraft?: boolean
  createdDate?: boolean
  updatedDate?: boolean
  resolvedDate?: boolean
  author?: boolean | Prisma.AuthorDefaultArgs<ExtArgs>
  book?: boolean | Prisma.Ticket$bookArgs<ExtArgs>
  assignedAdmin?: boolean | Prisma.Ticket$assignedAdminArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  authorId?: boolean
  category?: boolean
  bookId?: boolean
  header?: boolean
  detailDescription?: boolean
  status?: boolean
  assignedId?: boolean
  priorityScore?: boolean
  aiDraft?: boolean
  createdDate?: boolean
  updatedDate?: boolean
  resolvedDate?: boolean
  author?: boolean | Prisma.AuthorDefaultArgs<ExtArgs>
  book?: boolean | Prisma.Ticket$bookArgs<ExtArgs>
  assignedAdmin?: boolean | Prisma.Ticket$assignedAdminArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectScalar = {
  id?: boolean
  authorId?: boolean
  category?: boolean
  bookId?: boolean
  header?: boolean
  detailDescription?: boolean
  status?: boolean
  assignedId?: boolean
  priorityScore?: boolean
  aiDraft?: boolean
  createdDate?: boolean
  updatedDate?: boolean
  resolvedDate?: boolean
}

export type TicketOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "authorId" | "category" | "bookId" | "header" | "detailDescription" | "status" | "assignedId" | "priorityScore" | "aiDraft" | "createdDate" | "updatedDate" | "resolvedDate", ExtArgs["result"]["ticket"]>
export type TicketInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.AuthorDefaultArgs<ExtArgs>
  book?: boolean | Prisma.Ticket$bookArgs<ExtArgs>
  assignedAdmin?: boolean | Prisma.Ticket$assignedAdminArgs<ExtArgs>
  notes?: boolean | Prisma.Ticket$notesArgs<ExtArgs>
  messages?: boolean | Prisma.Ticket$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.TicketCountOutputTypeDefaultArgs<ExtArgs>
}
export type TicketIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.AuthorDefaultArgs<ExtArgs>
  book?: boolean | Prisma.Ticket$bookArgs<ExtArgs>
  assignedAdmin?: boolean | Prisma.Ticket$assignedAdminArgs<ExtArgs>
}
export type TicketIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.AuthorDefaultArgs<ExtArgs>
  book?: boolean | Prisma.Ticket$bookArgs<ExtArgs>
  assignedAdmin?: boolean | Prisma.Ticket$assignedAdminArgs<ExtArgs>
}

export type $TicketPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Ticket"
  objects: {
    author: Prisma.$AuthorPayload<ExtArgs>
    book: Prisma.$BookPayload<ExtArgs> | null
    assignedAdmin: Prisma.$AdminPayload<ExtArgs> | null
    notes: Prisma.$TicketNotePayload<ExtArgs>[]
    messages: Prisma.$TicketMessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    authorId: string
    category: string
    bookId: string | null
    header: string
    detailDescription: string
    status: string
    assignedId: string | null
    priorityScore: number | null
    aiDraft: string | null
    createdDate: Date
    updatedDate: Date
    resolvedDate: Date | null
  }, ExtArgs["result"]["ticket"]>
  composites: {}
}

export type TicketGetPayload<S extends boolean | null | undefined | TicketDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketPayload, S>

export type TicketCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketCountAggregateInputType | true
  }

export interface TicketDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Ticket'], meta: { name: 'Ticket' } }
  /**
   * Find zero or one Ticket that matches the filter.
   * @param {TicketFindUniqueArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ticket that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketFindUniqueOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindFirstArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindFirstOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tickets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tickets
   * const tickets = await prisma.ticket.findMany()
   * 
   * // Get first 10 Tickets
   * const tickets = await prisma.ticket.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketWithIdOnly = await prisma.ticket.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TicketFindManyArgs>(args?: Prisma.SelectSubset<T, TicketFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ticket.
   * @param {TicketCreateArgs} args - Arguments to create a Ticket.
   * @example
   * // Create one Ticket
   * const Ticket = await prisma.ticket.create({
   *   data: {
   *     // ... data to create a Ticket
   *   }
   * })
   * 
   */
  create<T extends TicketCreateArgs>(args: Prisma.SelectSubset<T, TicketCreateArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tickets.
   * @param {TicketCreateManyArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const ticket = await prisma.ticket.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tickets and returns the data saved in the database.
   * @param {TicketCreateManyAndReturnArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const ticket = await prisma.ticket.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tickets and only return the `id`
   * const ticketWithIdOnly = await prisma.ticket.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Ticket.
   * @param {TicketDeleteArgs} args - Arguments to delete one Ticket.
   * @example
   * // Delete one Ticket
   * const Ticket = await prisma.ticket.delete({
   *   where: {
   *     // ... filter to delete one Ticket
   *   }
   * })
   * 
   */
  delete<T extends TicketDeleteArgs>(args: Prisma.SelectSubset<T, TicketDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ticket.
   * @param {TicketUpdateArgs} args - Arguments to update one Ticket.
   * @example
   * // Update one Ticket
   * const ticket = await prisma.ticket.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketUpdateArgs>(args: Prisma.SelectSubset<T, TicketUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tickets.
   * @param {TicketDeleteManyArgs} args - Arguments to filter Tickets to delete.
   * @example
   * // Delete a few Tickets
   * const { count } = await prisma.ticket.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tickets
   * const ticket = await prisma.ticket.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets and returns the data updated in the database.
   * @param {TicketUpdateManyAndReturnArgs} args - Arguments to update many Tickets.
   * @example
   * // Update many Tickets
   * const ticket = await prisma.ticket.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tickets and only return the `id`
   * const ticketWithIdOnly = await prisma.ticket.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Ticket.
   * @param {TicketUpsertArgs} args - Arguments to update or create a Ticket.
   * @example
   * // Update or create a Ticket
   * const ticket = await prisma.ticket.upsert({
   *   create: {
   *     // ... data to create a Ticket
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ticket we want to update
   *   }
   * })
   */
  upsert<T extends TicketUpsertArgs>(args: Prisma.SelectSubset<T, TicketUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCountArgs} args - Arguments to filter Tickets to count.
   * @example
   * // Count the number of Tickets
   * const count = await prisma.ticket.count({
   *   where: {
   *     // ... the filter for the Tickets we want to count
   *   }
   * })
  **/
  count<T extends TicketCountArgs>(
    args?: Prisma.Subset<T, TicketCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketAggregateArgs>(args: Prisma.Subset<T, TicketAggregateArgs>): Prisma.PrismaPromise<GetTicketAggregateType<T>>

  /**
   * Group by Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketGroupByArgs['orderBy'] }
      : { orderBy?: TicketGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Ticket model
 */
readonly fields: TicketFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Ticket.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  author<T extends Prisma.AuthorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthorDefaultArgs<ExtArgs>>): Prisma.Prisma__AuthorClient<runtime.Types.Result.GetResult<Prisma.$AuthorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  book<T extends Prisma.Ticket$bookArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ticket$bookArgs<ExtArgs>>): Prisma.Prisma__BookClient<runtime.Types.Result.GetResult<Prisma.$BookPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  assignedAdmin<T extends Prisma.Ticket$assignedAdminArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ticket$assignedAdminArgs<ExtArgs>>): Prisma.Prisma__AdminClient<runtime.Types.Result.GetResult<Prisma.$AdminPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  notes<T extends Prisma.Ticket$notesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ticket$notesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  messages<T extends Prisma.Ticket$messagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ticket$messagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Ticket model
 */
export interface TicketFieldRefs {
  readonly id: Prisma.FieldRef<"Ticket", 'String'>
  readonly authorId: Prisma.FieldRef<"Ticket", 'String'>
  readonly category: Prisma.FieldRef<"Ticket", 'String'>
  readonly bookId: Prisma.FieldRef<"Ticket", 'String'>
  readonly header: Prisma.FieldRef<"Ticket", 'String'>
  readonly detailDescription: Prisma.FieldRef<"Ticket", 'String'>
  readonly status: Prisma.FieldRef<"Ticket", 'String'>
  readonly assignedId: Prisma.FieldRef<"Ticket", 'String'>
  readonly priorityScore: Prisma.FieldRef<"Ticket", 'Int'>
  readonly aiDraft: Prisma.FieldRef<"Ticket", 'String'>
  readonly createdDate: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly updatedDate: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly resolvedDate: Prisma.FieldRef<"Ticket", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Ticket findUnique
 */
export type TicketFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket findUniqueOrThrow
 */
export type TicketFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket findFirst
 */
export type TicketFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket findFirstOrThrow
 */
export type TicketFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket findMany
 */
export type TicketFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Tickets to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket create
 */
export type TicketCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The data needed to create a Ticket.
   */
  data: Prisma.XOR<Prisma.TicketCreateInput, Prisma.TicketUncheckedCreateInput>
}

/**
 * Ticket createMany
 */
export type TicketCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tickets.
   */
  data: Prisma.TicketCreateManyInput | Prisma.TicketCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Ticket createManyAndReturn
 */
export type TicketCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * The data used to create many Tickets.
   */
  data: Prisma.TicketCreateManyInput | Prisma.TicketCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Ticket update
 */
export type TicketUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The data needed to update a Ticket.
   */
  data: Prisma.XOR<Prisma.TicketUpdateInput, Prisma.TicketUncheckedUpdateInput>
  /**
   * Choose, which Ticket to update.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket updateMany
 */
export type TicketUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tickets.
   */
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyInput>
  /**
   * Filter which Tickets to update
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to update.
   */
  limit?: number
}

/**
 * Ticket updateManyAndReturn
 */
export type TicketUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * The data used to update Tickets.
   */
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyInput>
  /**
   * Filter which Tickets to update
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Ticket upsert
 */
export type TicketUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The filter to search for the Ticket to update in case it exists.
   */
  where: Prisma.TicketWhereUniqueInput
  /**
   * In case the Ticket found by the `where` argument doesn't exist, create a new Ticket with this data.
   */
  create: Prisma.XOR<Prisma.TicketCreateInput, Prisma.TicketUncheckedCreateInput>
  /**
   * In case the Ticket was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketUpdateInput, Prisma.TicketUncheckedUpdateInput>
}

/**
 * Ticket delete
 */
export type TicketDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter which Ticket to delete.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket deleteMany
 */
export type TicketDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tickets to delete
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to delete.
   */
  limit?: number
}

/**
 * Ticket.book
 */
export type Ticket$bookArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Book
   */
  select?: Prisma.BookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Book
   */
  omit?: Prisma.BookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookInclude<ExtArgs> | null
  where?: Prisma.BookWhereInput
}

/**
 * Ticket.assignedAdmin
 */
export type Ticket$assignedAdminArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Admin
   */
  select?: Prisma.AdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Admin
   */
  omit?: Prisma.AdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminInclude<ExtArgs> | null
  where?: Prisma.AdminWhereInput
}

/**
 * Ticket.notes
 */
export type Ticket$notesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  where?: Prisma.TicketNoteWhereInput
  orderBy?: Prisma.TicketNoteOrderByWithRelationInput | Prisma.TicketNoteOrderByWithRelationInput[]
  cursor?: Prisma.TicketNoteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TicketNoteScalarFieldEnum | Prisma.TicketNoteScalarFieldEnum[]
}

/**
 * Ticket.messages
 */
export type Ticket$messagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketMessage
   */
  select?: Prisma.TicketMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketMessage
   */
  omit?: Prisma.TicketMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketMessageInclude<ExtArgs> | null
  where?: Prisma.TicketMessageWhereInput
  orderBy?: Prisma.TicketMessageOrderByWithRelationInput | Prisma.TicketMessageOrderByWithRelationInput[]
  cursor?: Prisma.TicketMessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TicketMessageScalarFieldEnum | Prisma.TicketMessageScalarFieldEnum[]
}

/**
 * Ticket without action
 */
export type TicketDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
}
