
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TicketNote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TicketNote
 * 
 */
export type TicketNoteModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketNotePayload>

export type AggregateTicketNote = {
  _count: TicketNoteCountAggregateOutputType | null
  _min: TicketNoteMinAggregateOutputType | null
  _max: TicketNoteMaxAggregateOutputType | null
}

export type TicketNoteMinAggregateOutputType = {
  id: string | null
  ticketId: string | null
  adminId: string | null
  message: string | null
  visibility: string | null
}

export type TicketNoteMaxAggregateOutputType = {
  id: string | null
  ticketId: string | null
  adminId: string | null
  message: string | null
  visibility: string | null
}

export type TicketNoteCountAggregateOutputType = {
  id: number
  ticketId: number
  adminId: number
  message: number
  visibility: number
  _all: number
}


export type TicketNoteMinAggregateInputType = {
  id?: true
  ticketId?: true
  adminId?: true
  message?: true
  visibility?: true
}

export type TicketNoteMaxAggregateInputType = {
  id?: true
  ticketId?: true
  adminId?: true
  message?: true
  visibility?: true
}

export type TicketNoteCountAggregateInputType = {
  id?: true
  ticketId?: true
  adminId?: true
  message?: true
  visibility?: true
  _all?: true
}

export type TicketNoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketNote to aggregate.
   */
  where?: Prisma.TicketNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketNotes to fetch.
   */
  orderBy?: Prisma.TicketNoteOrderByWithRelationInput | Prisma.TicketNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TicketNotes
  **/
  _count?: true | TicketNoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketNoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketNoteMaxAggregateInputType
}

export type GetTicketNoteAggregateType<T extends TicketNoteAggregateArgs> = {
      [P in keyof T & keyof AggregateTicketNote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicketNote[P]>
    : Prisma.GetScalarType<T[P], AggregateTicketNote[P]>
}




export type TicketNoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketNoteWhereInput
  orderBy?: Prisma.TicketNoteOrderByWithAggregationInput | Prisma.TicketNoteOrderByWithAggregationInput[]
  by: Prisma.TicketNoteScalarFieldEnum[] | Prisma.TicketNoteScalarFieldEnum
  having?: Prisma.TicketNoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketNoteCountAggregateInputType | true
  _min?: TicketNoteMinAggregateInputType
  _max?: TicketNoteMaxAggregateInputType
}

export type TicketNoteGroupByOutputType = {
  id: string
  ticketId: string
  adminId: string
  message: string
  visibility: string
  _count: TicketNoteCountAggregateOutputType | null
  _min: TicketNoteMinAggregateOutputType | null
  _max: TicketNoteMaxAggregateOutputType | null
}

export type GetTicketNoteGroupByPayload<T extends TicketNoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketNoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketNoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketNoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketNoteGroupByOutputType[P]>
      }
    >
  >



export type TicketNoteWhereInput = {
  AND?: Prisma.TicketNoteWhereInput | Prisma.TicketNoteWhereInput[]
  OR?: Prisma.TicketNoteWhereInput[]
  NOT?: Prisma.TicketNoteWhereInput | Prisma.TicketNoteWhereInput[]
  id?: Prisma.StringFilter<"TicketNote"> | string
  ticketId?: Prisma.StringFilter<"TicketNote"> | string
  adminId?: Prisma.StringFilter<"TicketNote"> | string
  message?: Prisma.StringFilter<"TicketNote"> | string
  visibility?: Prisma.StringFilter<"TicketNote"> | string
  ticket?: Prisma.XOR<Prisma.TicketScalarRelationFilter, Prisma.TicketWhereInput>
  admin?: Prisma.XOR<Prisma.AdminScalarRelationFilter, Prisma.AdminWhereInput>
}

export type TicketNoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  ticket?: Prisma.TicketOrderByWithRelationInput
  admin?: Prisma.AdminOrderByWithRelationInput
}

export type TicketNoteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TicketNoteWhereInput | Prisma.TicketNoteWhereInput[]
  OR?: Prisma.TicketNoteWhereInput[]
  NOT?: Prisma.TicketNoteWhereInput | Prisma.TicketNoteWhereInput[]
  ticketId?: Prisma.StringFilter<"TicketNote"> | string
  adminId?: Prisma.StringFilter<"TicketNote"> | string
  message?: Prisma.StringFilter<"TicketNote"> | string
  visibility?: Prisma.StringFilter<"TicketNote"> | string
  ticket?: Prisma.XOR<Prisma.TicketScalarRelationFilter, Prisma.TicketWhereInput>
  admin?: Prisma.XOR<Prisma.AdminScalarRelationFilter, Prisma.AdminWhereInput>
}, "id">

export type TicketNoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  _count?: Prisma.TicketNoteCountOrderByAggregateInput
  _max?: Prisma.TicketNoteMaxOrderByAggregateInput
  _min?: Prisma.TicketNoteMinOrderByAggregateInput
}

export type TicketNoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketNoteScalarWhereWithAggregatesInput | Prisma.TicketNoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketNoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketNoteScalarWhereWithAggregatesInput | Prisma.TicketNoteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TicketNote"> | string
  ticketId?: Prisma.StringWithAggregatesFilter<"TicketNote"> | string
  adminId?: Prisma.StringWithAggregatesFilter<"TicketNote"> | string
  message?: Prisma.StringWithAggregatesFilter<"TicketNote"> | string
  visibility?: Prisma.StringWithAggregatesFilter<"TicketNote"> | string
}

export type TicketNoteCreateInput = {
  id?: string
  message: string
  visibility: string
  ticket: Prisma.TicketCreateNestedOneWithoutNotesInput
  admin: Prisma.AdminCreateNestedOneWithoutTicketNotesInput
}

export type TicketNoteUncheckedCreateInput = {
  id?: string
  ticketId: string
  adminId: string
  message: string
  visibility: string
}

export type TicketNoteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
  ticket?: Prisma.TicketUpdateOneRequiredWithoutNotesNestedInput
  admin?: Prisma.AdminUpdateOneRequiredWithoutTicketNotesNestedInput
}

export type TicketNoteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
  adminId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketNoteCreateManyInput = {
  id?: string
  ticketId: string
  adminId: string
  message: string
  visibility: string
}

export type TicketNoteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketNoteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
  adminId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketNoteListRelationFilter = {
  every?: Prisma.TicketNoteWhereInput
  some?: Prisma.TicketNoteWhereInput
  none?: Prisma.TicketNoteWhereInput
}

export type TicketNoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketNoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
}

export type TicketNoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
}

export type TicketNoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
}

export type TicketNoteCreateNestedManyWithoutAdminInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutAdminInput, Prisma.TicketNoteUncheckedCreateWithoutAdminInput> | Prisma.TicketNoteCreateWithoutAdminInput[] | Prisma.TicketNoteUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutAdminInput | Prisma.TicketNoteCreateOrConnectWithoutAdminInput[]
  createMany?: Prisma.TicketNoteCreateManyAdminInputEnvelope
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
}

export type TicketNoteUncheckedCreateNestedManyWithoutAdminInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutAdminInput, Prisma.TicketNoteUncheckedCreateWithoutAdminInput> | Prisma.TicketNoteCreateWithoutAdminInput[] | Prisma.TicketNoteUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutAdminInput | Prisma.TicketNoteCreateOrConnectWithoutAdminInput[]
  createMany?: Prisma.TicketNoteCreateManyAdminInputEnvelope
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
}

export type TicketNoteUpdateManyWithoutAdminNestedInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutAdminInput, Prisma.TicketNoteUncheckedCreateWithoutAdminInput> | Prisma.TicketNoteCreateWithoutAdminInput[] | Prisma.TicketNoteUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutAdminInput | Prisma.TicketNoteCreateOrConnectWithoutAdminInput[]
  upsert?: Prisma.TicketNoteUpsertWithWhereUniqueWithoutAdminInput | Prisma.TicketNoteUpsertWithWhereUniqueWithoutAdminInput[]
  createMany?: Prisma.TicketNoteCreateManyAdminInputEnvelope
  set?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  disconnect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  delete?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  update?: Prisma.TicketNoteUpdateWithWhereUniqueWithoutAdminInput | Prisma.TicketNoteUpdateWithWhereUniqueWithoutAdminInput[]
  updateMany?: Prisma.TicketNoteUpdateManyWithWhereWithoutAdminInput | Prisma.TicketNoteUpdateManyWithWhereWithoutAdminInput[]
  deleteMany?: Prisma.TicketNoteScalarWhereInput | Prisma.TicketNoteScalarWhereInput[]
}

export type TicketNoteUncheckedUpdateManyWithoutAdminNestedInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutAdminInput, Prisma.TicketNoteUncheckedCreateWithoutAdminInput> | Prisma.TicketNoteCreateWithoutAdminInput[] | Prisma.TicketNoteUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutAdminInput | Prisma.TicketNoteCreateOrConnectWithoutAdminInput[]
  upsert?: Prisma.TicketNoteUpsertWithWhereUniqueWithoutAdminInput | Prisma.TicketNoteUpsertWithWhereUniqueWithoutAdminInput[]
  createMany?: Prisma.TicketNoteCreateManyAdminInputEnvelope
  set?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  disconnect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  delete?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  update?: Prisma.TicketNoteUpdateWithWhereUniqueWithoutAdminInput | Prisma.TicketNoteUpdateWithWhereUniqueWithoutAdminInput[]
  updateMany?: Prisma.TicketNoteUpdateManyWithWhereWithoutAdminInput | Prisma.TicketNoteUpdateManyWithWhereWithoutAdminInput[]
  deleteMany?: Prisma.TicketNoteScalarWhereInput | Prisma.TicketNoteScalarWhereInput[]
}

export type TicketNoteCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutTicketInput, Prisma.TicketNoteUncheckedCreateWithoutTicketInput> | Prisma.TicketNoteCreateWithoutTicketInput[] | Prisma.TicketNoteUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutTicketInput | Prisma.TicketNoteCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.TicketNoteCreateManyTicketInputEnvelope
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
}

export type TicketNoteUncheckedCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutTicketInput, Prisma.TicketNoteUncheckedCreateWithoutTicketInput> | Prisma.TicketNoteCreateWithoutTicketInput[] | Prisma.TicketNoteUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutTicketInput | Prisma.TicketNoteCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.TicketNoteCreateManyTicketInputEnvelope
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
}

export type TicketNoteUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutTicketInput, Prisma.TicketNoteUncheckedCreateWithoutTicketInput> | Prisma.TicketNoteCreateWithoutTicketInput[] | Prisma.TicketNoteUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutTicketInput | Prisma.TicketNoteCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.TicketNoteUpsertWithWhereUniqueWithoutTicketInput | Prisma.TicketNoteUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.TicketNoteCreateManyTicketInputEnvelope
  set?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  disconnect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  delete?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  update?: Prisma.TicketNoteUpdateWithWhereUniqueWithoutTicketInput | Prisma.TicketNoteUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.TicketNoteUpdateManyWithWhereWithoutTicketInput | Prisma.TicketNoteUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.TicketNoteScalarWhereInput | Prisma.TicketNoteScalarWhereInput[]
}

export type TicketNoteUncheckedUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.TicketNoteCreateWithoutTicketInput, Prisma.TicketNoteUncheckedCreateWithoutTicketInput> | Prisma.TicketNoteCreateWithoutTicketInput[] | Prisma.TicketNoteUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketNoteCreateOrConnectWithoutTicketInput | Prisma.TicketNoteCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.TicketNoteUpsertWithWhereUniqueWithoutTicketInput | Prisma.TicketNoteUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.TicketNoteCreateManyTicketInputEnvelope
  set?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  disconnect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  delete?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  connect?: Prisma.TicketNoteWhereUniqueInput | Prisma.TicketNoteWhereUniqueInput[]
  update?: Prisma.TicketNoteUpdateWithWhereUniqueWithoutTicketInput | Prisma.TicketNoteUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.TicketNoteUpdateManyWithWhereWithoutTicketInput | Prisma.TicketNoteUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.TicketNoteScalarWhereInput | Prisma.TicketNoteScalarWhereInput[]
}

export type TicketNoteCreateWithoutAdminInput = {
  id?: string
  message: string
  visibility: string
  ticket: Prisma.TicketCreateNestedOneWithoutNotesInput
}

export type TicketNoteUncheckedCreateWithoutAdminInput = {
  id?: string
  ticketId: string
  message: string
  visibility: string
}

export type TicketNoteCreateOrConnectWithoutAdminInput = {
  where: Prisma.TicketNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketNoteCreateWithoutAdminInput, Prisma.TicketNoteUncheckedCreateWithoutAdminInput>
}

export type TicketNoteCreateManyAdminInputEnvelope = {
  data: Prisma.TicketNoteCreateManyAdminInput | Prisma.TicketNoteCreateManyAdminInput[]
  skipDuplicates?: boolean
}

export type TicketNoteUpsertWithWhereUniqueWithoutAdminInput = {
  where: Prisma.TicketNoteWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketNoteUpdateWithoutAdminInput, Prisma.TicketNoteUncheckedUpdateWithoutAdminInput>
  create: Prisma.XOR<Prisma.TicketNoteCreateWithoutAdminInput, Prisma.TicketNoteUncheckedCreateWithoutAdminInput>
}

export type TicketNoteUpdateWithWhereUniqueWithoutAdminInput = {
  where: Prisma.TicketNoteWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketNoteUpdateWithoutAdminInput, Prisma.TicketNoteUncheckedUpdateWithoutAdminInput>
}

export type TicketNoteUpdateManyWithWhereWithoutAdminInput = {
  where: Prisma.TicketNoteScalarWhereInput
  data: Prisma.XOR<Prisma.TicketNoteUpdateManyMutationInput, Prisma.TicketNoteUncheckedUpdateManyWithoutAdminInput>
}

export type TicketNoteScalarWhereInput = {
  AND?: Prisma.TicketNoteScalarWhereInput | Prisma.TicketNoteScalarWhereInput[]
  OR?: Prisma.TicketNoteScalarWhereInput[]
  NOT?: Prisma.TicketNoteScalarWhereInput | Prisma.TicketNoteScalarWhereInput[]
  id?: Prisma.StringFilter<"TicketNote"> | string
  ticketId?: Prisma.StringFilter<"TicketNote"> | string
  adminId?: Prisma.StringFilter<"TicketNote"> | string
  message?: Prisma.StringFilter<"TicketNote"> | string
  visibility?: Prisma.StringFilter<"TicketNote"> | string
}

export type TicketNoteCreateWithoutTicketInput = {
  id?: string
  message: string
  visibility: string
  admin: Prisma.AdminCreateNestedOneWithoutTicketNotesInput
}

export type TicketNoteUncheckedCreateWithoutTicketInput = {
  id?: string
  adminId: string
  message: string
  visibility: string
}

export type TicketNoteCreateOrConnectWithoutTicketInput = {
  where: Prisma.TicketNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketNoteCreateWithoutTicketInput, Prisma.TicketNoteUncheckedCreateWithoutTicketInput>
}

export type TicketNoteCreateManyTicketInputEnvelope = {
  data: Prisma.TicketNoteCreateManyTicketInput | Prisma.TicketNoteCreateManyTicketInput[]
  skipDuplicates?: boolean
}

export type TicketNoteUpsertWithWhereUniqueWithoutTicketInput = {
  where: Prisma.TicketNoteWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketNoteUpdateWithoutTicketInput, Prisma.TicketNoteUncheckedUpdateWithoutTicketInput>
  create: Prisma.XOR<Prisma.TicketNoteCreateWithoutTicketInput, Prisma.TicketNoteUncheckedCreateWithoutTicketInput>
}

export type TicketNoteUpdateWithWhereUniqueWithoutTicketInput = {
  where: Prisma.TicketNoteWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketNoteUpdateWithoutTicketInput, Prisma.TicketNoteUncheckedUpdateWithoutTicketInput>
}

export type TicketNoteUpdateManyWithWhereWithoutTicketInput = {
  where: Prisma.TicketNoteScalarWhereInput
  data: Prisma.XOR<Prisma.TicketNoteUpdateManyMutationInput, Prisma.TicketNoteUncheckedUpdateManyWithoutTicketInput>
}

export type TicketNoteCreateManyAdminInput = {
  id?: string
  ticketId: string
  message: string
  visibility: string
}

export type TicketNoteUpdateWithoutAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
  ticket?: Prisma.TicketUpdateOneRequiredWithoutNotesNestedInput
}

export type TicketNoteUncheckedUpdateWithoutAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketNoteUncheckedUpdateManyWithoutAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketNoteCreateManyTicketInput = {
  id?: string
  adminId: string
  message: string
  visibility: string
}

export type TicketNoteUpdateWithoutTicketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
  admin?: Prisma.AdminUpdateOneRequiredWithoutTicketNotesNestedInput
}

export type TicketNoteUncheckedUpdateWithoutTicketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adminId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketNoteUncheckedUpdateManyWithoutTicketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adminId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TicketNoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticketId?: boolean
  adminId?: boolean
  message?: boolean
  visibility?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  admin?: boolean | Prisma.AdminDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketNote"]>

export type TicketNoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticketId?: boolean
  adminId?: boolean
  message?: boolean
  visibility?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  admin?: boolean | Prisma.AdminDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketNote"]>

export type TicketNoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticketId?: boolean
  adminId?: boolean
  message?: boolean
  visibility?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  admin?: boolean | Prisma.AdminDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketNote"]>

export type TicketNoteSelectScalar = {
  id?: boolean
  ticketId?: boolean
  adminId?: boolean
  message?: boolean
  visibility?: boolean
}

export type TicketNoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ticketId" | "adminId" | "message" | "visibility", ExtArgs["result"]["ticketNote"]>
export type TicketNoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  admin?: boolean | Prisma.AdminDefaultArgs<ExtArgs>
}
export type TicketNoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  admin?: boolean | Prisma.AdminDefaultArgs<ExtArgs>
}
export type TicketNoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  admin?: boolean | Prisma.AdminDefaultArgs<ExtArgs>
}

export type $TicketNotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TicketNote"
  objects: {
    ticket: Prisma.$TicketPayload<ExtArgs>
    admin: Prisma.$AdminPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ticketId: string
    adminId: string
    message: string
    visibility: string
  }, ExtArgs["result"]["ticketNote"]>
  composites: {}
}

export type TicketNoteGetPayload<S extends boolean | null | undefined | TicketNoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketNotePayload, S>

export type TicketNoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketNoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketNoteCountAggregateInputType | true
  }

export interface TicketNoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TicketNote'], meta: { name: 'TicketNote' } }
  /**
   * Find zero or one TicketNote that matches the filter.
   * @param {TicketNoteFindUniqueArgs} args - Arguments to find a TicketNote
   * @example
   * // Get one TicketNote
   * const ticketNote = await prisma.ticketNote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketNoteFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketNoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TicketNote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketNoteFindUniqueOrThrowArgs} args - Arguments to find a TicketNote
   * @example
   * // Get one TicketNote
   * const ticketNote = await prisma.ticketNote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketNoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketNoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketNote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketNoteFindFirstArgs} args - Arguments to find a TicketNote
   * @example
   * // Get one TicketNote
   * const ticketNote = await prisma.ticketNote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketNoteFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketNoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketNote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketNoteFindFirstOrThrowArgs} args - Arguments to find a TicketNote
   * @example
   * // Get one TicketNote
   * const ticketNote = await prisma.ticketNote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketNoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketNoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TicketNotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketNoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TicketNotes
   * const ticketNotes = await prisma.ticketNote.findMany()
   * 
   * // Get first 10 TicketNotes
   * const ticketNotes = await prisma.ticketNote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketNoteWithIdOnly = await prisma.ticketNote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TicketNoteFindManyArgs>(args?: Prisma.SelectSubset<T, TicketNoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TicketNote.
   * @param {TicketNoteCreateArgs} args - Arguments to create a TicketNote.
   * @example
   * // Create one TicketNote
   * const TicketNote = await prisma.ticketNote.create({
   *   data: {
   *     // ... data to create a TicketNote
   *   }
   * })
   * 
   */
  create<T extends TicketNoteCreateArgs>(args: Prisma.SelectSubset<T, TicketNoteCreateArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TicketNotes.
   * @param {TicketNoteCreateManyArgs} args - Arguments to create many TicketNotes.
   * @example
   * // Create many TicketNotes
   * const ticketNote = await prisma.ticketNote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketNoteCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketNoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TicketNotes and returns the data saved in the database.
   * @param {TicketNoteCreateManyAndReturnArgs} args - Arguments to create many TicketNotes.
   * @example
   * // Create many TicketNotes
   * const ticketNote = await prisma.ticketNote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TicketNotes and only return the `id`
   * const ticketNoteWithIdOnly = await prisma.ticketNote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketNoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketNoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TicketNote.
   * @param {TicketNoteDeleteArgs} args - Arguments to delete one TicketNote.
   * @example
   * // Delete one TicketNote
   * const TicketNote = await prisma.ticketNote.delete({
   *   where: {
   *     // ... filter to delete one TicketNote
   *   }
   * })
   * 
   */
  delete<T extends TicketNoteDeleteArgs>(args: Prisma.SelectSubset<T, TicketNoteDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TicketNote.
   * @param {TicketNoteUpdateArgs} args - Arguments to update one TicketNote.
   * @example
   * // Update one TicketNote
   * const ticketNote = await prisma.ticketNote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketNoteUpdateArgs>(args: Prisma.SelectSubset<T, TicketNoteUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TicketNotes.
   * @param {TicketNoteDeleteManyArgs} args - Arguments to filter TicketNotes to delete.
   * @example
   * // Delete a few TicketNotes
   * const { count } = await prisma.ticketNote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketNoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketNoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketNoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TicketNotes
   * const ticketNote = await prisma.ticketNote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketNoteUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketNoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketNotes and returns the data updated in the database.
   * @param {TicketNoteUpdateManyAndReturnArgs} args - Arguments to update many TicketNotes.
   * @example
   * // Update many TicketNotes
   * const ticketNote = await prisma.ticketNote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TicketNotes and only return the `id`
   * const ticketNoteWithIdOnly = await prisma.ticketNote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketNoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketNoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TicketNote.
   * @param {TicketNoteUpsertArgs} args - Arguments to update or create a TicketNote.
   * @example
   * // Update or create a TicketNote
   * const ticketNote = await prisma.ticketNote.upsert({
   *   create: {
   *     // ... data to create a TicketNote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TicketNote we want to update
   *   }
   * })
   */
  upsert<T extends TicketNoteUpsertArgs>(args: Prisma.SelectSubset<T, TicketNoteUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketNoteClient<runtime.Types.Result.GetResult<Prisma.$TicketNotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TicketNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketNoteCountArgs} args - Arguments to filter TicketNotes to count.
   * @example
   * // Count the number of TicketNotes
   * const count = await prisma.ticketNote.count({
   *   where: {
   *     // ... the filter for the TicketNotes we want to count
   *   }
   * })
  **/
  count<T extends TicketNoteCountArgs>(
    args?: Prisma.Subset<T, TicketNoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketNoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TicketNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketNoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketNoteAggregateArgs>(args: Prisma.Subset<T, TicketNoteAggregateArgs>): Prisma.PrismaPromise<GetTicketNoteAggregateType<T>>

  /**
   * Group by TicketNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketNoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketNoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketNoteGroupByArgs['orderBy'] }
      : { orderBy?: TicketNoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketNoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketNoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TicketNote model
 */
readonly fields: TicketNoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TicketNote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketNoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ticket<T extends Prisma.TicketDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TicketDefaultArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  admin<T extends Prisma.AdminDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AdminDefaultArgs<ExtArgs>>): Prisma.Prisma__AdminClient<runtime.Types.Result.GetResult<Prisma.$AdminPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TicketNote model
 */
export interface TicketNoteFieldRefs {
  readonly id: Prisma.FieldRef<"TicketNote", 'String'>
  readonly ticketId: Prisma.FieldRef<"TicketNote", 'String'>
  readonly adminId: Prisma.FieldRef<"TicketNote", 'String'>
  readonly message: Prisma.FieldRef<"TicketNote", 'String'>
  readonly visibility: Prisma.FieldRef<"TicketNote", 'String'>
}
    

// Custom InputTypes
/**
 * TicketNote findUnique
 */
export type TicketNoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * Filter, which TicketNote to fetch.
   */
  where: Prisma.TicketNoteWhereUniqueInput
}

/**
 * TicketNote findUniqueOrThrow
 */
export type TicketNoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * Filter, which TicketNote to fetch.
   */
  where: Prisma.TicketNoteWhereUniqueInput
}

/**
 * TicketNote findFirst
 */
export type TicketNoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * Filter, which TicketNote to fetch.
   */
  where?: Prisma.TicketNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketNotes to fetch.
   */
  orderBy?: Prisma.TicketNoteOrderByWithRelationInput | Prisma.TicketNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketNotes.
   */
  cursor?: Prisma.TicketNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketNotes.
   */
  distinct?: Prisma.TicketNoteScalarFieldEnum | Prisma.TicketNoteScalarFieldEnum[]
}

/**
 * TicketNote findFirstOrThrow
 */
export type TicketNoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * Filter, which TicketNote to fetch.
   */
  where?: Prisma.TicketNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketNotes to fetch.
   */
  orderBy?: Prisma.TicketNoteOrderByWithRelationInput | Prisma.TicketNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketNotes.
   */
  cursor?: Prisma.TicketNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketNotes.
   */
  distinct?: Prisma.TicketNoteScalarFieldEnum | Prisma.TicketNoteScalarFieldEnum[]
}

/**
 * TicketNote findMany
 */
export type TicketNoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * Filter, which TicketNotes to fetch.
   */
  where?: Prisma.TicketNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketNotes to fetch.
   */
  orderBy?: Prisma.TicketNoteOrderByWithRelationInput | Prisma.TicketNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TicketNotes.
   */
  cursor?: Prisma.TicketNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketNotes.
   */
  distinct?: Prisma.TicketNoteScalarFieldEnum | Prisma.TicketNoteScalarFieldEnum[]
}

/**
 * TicketNote create
 */
export type TicketNoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * The data needed to create a TicketNote.
   */
  data: Prisma.XOR<Prisma.TicketNoteCreateInput, Prisma.TicketNoteUncheckedCreateInput>
}

/**
 * TicketNote createMany
 */
export type TicketNoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TicketNotes.
   */
  data: Prisma.TicketNoteCreateManyInput | Prisma.TicketNoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TicketNote createManyAndReturn
 */
export type TicketNoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * The data used to create many TicketNotes.
   */
  data: Prisma.TicketNoteCreateManyInput | Prisma.TicketNoteCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TicketNote update
 */
export type TicketNoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * The data needed to update a TicketNote.
   */
  data: Prisma.XOR<Prisma.TicketNoteUpdateInput, Prisma.TicketNoteUncheckedUpdateInput>
  /**
   * Choose, which TicketNote to update.
   */
  where: Prisma.TicketNoteWhereUniqueInput
}

/**
 * TicketNote updateMany
 */
export type TicketNoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TicketNotes.
   */
  data: Prisma.XOR<Prisma.TicketNoteUpdateManyMutationInput, Prisma.TicketNoteUncheckedUpdateManyInput>
  /**
   * Filter which TicketNotes to update
   */
  where?: Prisma.TicketNoteWhereInput
  /**
   * Limit how many TicketNotes to update.
   */
  limit?: number
}

/**
 * TicketNote updateManyAndReturn
 */
export type TicketNoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * The data used to update TicketNotes.
   */
  data: Prisma.XOR<Prisma.TicketNoteUpdateManyMutationInput, Prisma.TicketNoteUncheckedUpdateManyInput>
  /**
   * Filter which TicketNotes to update
   */
  where?: Prisma.TicketNoteWhereInput
  /**
   * Limit how many TicketNotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TicketNote upsert
 */
export type TicketNoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * The filter to search for the TicketNote to update in case it exists.
   */
  where: Prisma.TicketNoteWhereUniqueInput
  /**
   * In case the TicketNote found by the `where` argument doesn't exist, create a new TicketNote with this data.
   */
  create: Prisma.XOR<Prisma.TicketNoteCreateInput, Prisma.TicketNoteUncheckedCreateInput>
  /**
   * In case the TicketNote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketNoteUpdateInput, Prisma.TicketNoteUncheckedUpdateInput>
}

/**
 * TicketNote delete
 */
export type TicketNoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
  /**
   * Filter which TicketNote to delete.
   */
  where: Prisma.TicketNoteWhereUniqueInput
}

/**
 * TicketNote deleteMany
 */
export type TicketNoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketNotes to delete
   */
  where?: Prisma.TicketNoteWhereInput
  /**
   * Limit how many TicketNotes to delete.
   */
  limit?: number
}

/**
 * TicketNote without action
 */
export type TicketNoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketNote
   */
  select?: Prisma.TicketNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketNote
   */
  omit?: Prisma.TicketNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketNoteInclude<ExtArgs> | null
}
